const moves = {
	growl: {name: "Growl", moveType: moveTypes.status, type: types.normal, bp: 0, accuracy: 100, pp: 40},
	tailwhip: {name: "Tail Whip", moveType: moveTypes.status, type: types.normal, bp: 0, accuracy: 100, pp: 30},
	leer: {name: "Leer", moveType: moveTypes.status, type: types.normal, bp: 0, accuracy: 100, pp: 30},
	tackle: {name: "Tackle", moveType: moveTypes.physical, type: types.normal, bp: 40, accuracy: 100, pp: 35},
	vinewhip: {name: "Vine Whip", moveType: moveTypes.physical, type: types.grass, bp: 45, accuracy: 100, pp: 25},
	rockthrow: {name: "Rock Throw", moveType: moveTypes.physical, type: types.rock, bp: 50, accuracy: 90, pp: 15},
	watergun: {name: "Water Gun", moveType: moveTypes.special, type: types.water, bp: 40, accuracy: 100, pp: 25},
	bubblebeam: {name: "Bubble Beam", moveType: moveTypes.special, type: types.water, bp: 65, accuracy: 100, pp: 20},
	dragonclaw: {name: "Dragon Claw", moveType: moveTypes.physical, type: types.dragon, bp: 80, accuracy: 100, pp: 15},
	ember: {name: "Ember", moveType: moveTypes.special, type: types.fire, bp: 40, accuracy: 100, pp: 25},
	bite: {name: "Bite", moveType: moveTypes.physical, type: types.dark, bp: 60, accuracy: 100, pp: 25},
	crunch: {name: "Crunch", moveType: moveTypes.physical, type: types.dark, bp: 80, accuracy: 100, pp: 15},
	harden: {name: "Harden", moveType: moveTypes.status, type: types.normal, bp: 0, accuracy: 0, pp: 30},
	growth: {name: "Growth", moveType: moveTypes.status, type: types.normal, bp: 0, accuracy: 0, pp: 20},
	leechseed: {name: "Leech Seed", moveType: moveTypes.status, type: types.grass, bp: 0, accuracy: 90, pp: 10},
	razorleaf: {name: "Razor Leaf", moveType: moveTypes.physical, type: types.grass, bp: 55, accuracy: 95, pp: 25},
	poisonpowder: {name: "Poison Powder", moveType: moveTypes.status, type: types.poison, bp: 0, accuracy: 75, pp: 35},
	sleeppowder: {name: "Sleep Powder", moveType: moveTypes.status, type: types.grass, bp: 0, accuracy: 75, pp: 15},
	takedown: {name: "Take Down", moveType: moveTypes.physical, type: types.normal, bp: 90, accuracy: 80, pp: 20},
	magicalleaf: {name: "Magical Leaf", moveType: moveTypes.special, type: types.grass, bp: 60, accuracy: 0, pp: 20},
	sludgewave: {name: "Sludge Wave", moveType: moveTypes.special, type: types.poison, bp: 95, accuracy: 100, pp: 10},
	doubleedge: {name: "Double Edge", moveType: moveTypes.physical, type: types.normal, bp: 120, accuracy: 100, pp: 15},
	solarbeam: {name: "Solar Beam", moveType: moveTypes.special, type: types.grass, bp: 120, accuracy: 100, pp: 10},
	synthesis: {name: "Synthesis", moveType: moveTypes.status, type: types.grass, bp: 0, accuracy: 0, pp: 5},
	amnesia: {name: "Amnesia", moveType: moveTypes.status, type: types.psychic, bp: 0, accuracy: 0, pp: 20},
	powerwhip: {name: "Power Whip", moveType: moveTypes.physical, type: types.grass, bp: 120, accuracy: 85, pp: 10},
	earthquake: {name: "Earthquake", moveType: moveTypes.physical, type: types.ground, bp: 100, accuracy: 100, pp: 10},
};